library(Seurat)
library(Biostrings)
library("LSD")
require(ggplot2)
require(ggseqlogo)
library("dplyr")
library(pheatmap)
library(corrplot)
#library("DESeq2")
library("seqinr")
library("vsn")
library(pcaMethods)
library(SC3)
library(scater)
library(SingleCellExperiment)
library(pheatmap)
library(mclust)
library("glmnet")
require(data.table)
library(Seurat)
library("ggpubr")
library(scales)
library("yaml")
library(RColorBrewer)
library("ggalluvial")
library(reshape2)
library("cowplot")
library("stringr")
library(seqinr)  
library(msa)
library(ape)
library(alakazam)
library(shazam)
library("xlsx")
library("Peptides")
library("icesTAF")
library("treeio")
library("ggtree")
#library("phytools")
library(alakazam)
library(igraph)
library(dplyr)
library("Rphylip")
library("AnnotationDbi")
library("org.Hs.eg.db")
library(network)
library(sna)

source("./Conf.R")
source("./Utilities.R")

theme_set(theme_get() + theme_pubclean())

knitr::opts_chunk$set(cache = TRUE, warning = FALSE, 
                      message = FALSE, cache.lazy = FALSE)
